# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Allison Fleischer
logo: /img/site/avatar_medium.png
email: allisonfleisch@gmail.com
description: >
  Hi, I make music and stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://allisonfleischer.com" # the base hostname & protocol for your site
twitter_username: AllisonFleisch
twitter:
  username: AllisonFleisch # Alternate Twitter format used for jekyll-seo
github_username: AllisonFleischer
feed:
  path: atom.xml

repository: "AllisonFleischer/AllisonFleischer.github.io"

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
